window.GHIBLI_POSTERS = {
  "Nausicaä of the Valley of the Wind": "img/ghibli/nausicaa.jpg",
  "Castle in the Sky": "img/ghibli/castle_in_the_sky.jpg",
  "Grave of the Fireflies": "img/ghibli/grave_of_the_fireflies.jpg",
  "My Neighbor Totoro": "img/ghibli/my_neighbor_totoro.jpg",
  "Kiki's Delivery Service": "img/ghibli/kiki_delivery_service.jpg",
  "Only Yesterday": "img/ghibli/only_yesterday.jpg",
  "Porco Rosso": "img/ghibli/porco_rosso.jpg",
  "Ocean Waves": "img/ghibli/ocean_waves.jpg",
  "Pom Poko": "img/ghibli/pom_poko.jpg",
  "Whisper of the Heart": "img/ghibli/whisper_of_the_heart.jpg",
  "Princess Mononoke": "img/ghibli/princess_mononoke.png",
  "My Neighbors the Yamadas": "img/ghibli/my_neighbors_the_yamadas.jpg",
  "Spirited Away": "img/ghibli/spirited_away.jpg",
  "The Cat Returns": "img/ghibli/the_cat_returns.jpg",
  "Howl's Moving Castle": "img/ghibli/howls_moving_castle.jpg",
  "Tales from Earthsea": "img/ghibli/tales_from_earthsea.jpg",
  "Ponyo": "img/ghibli/ponyo.jpg",
  "Arrietty": "img/ghibli/arrietty.jpg",
  "From Up on Poppy Hill": "img/ghibli/from_up_on_poppy_hill.jpg",
  "The Wind Rises": "img/ghibli/the_wind_rises.png",
  "The Tale of the Princess Kaguya": "img/ghibli/princess_kaguya.jpg",
  "When Marnie Was There": "img/ghibli/when_marnie_was_there.jpg",
  "Earwig and the Witch": "img/ghibli/earwig_and_the_witch.jpg"
};
